### ISSUE TITLE
Why this error??? 'spacing' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by loverde-co** [shuhrat10/STRatingControl#11]
In your README file, it mentioned 2 times that ```spacing``` is accessible.
But when i try to use it. BAM! ```'spacing' is inaccessible due to 'internal' protection level```
I just already track your parameter, and it is tacking me to UIKit > UIStackView, thats conflicting to your IBDesignable when i try to access thru code.

**Comment by shuhrat10** [comment]
Daniel, I'm very sorry to hear that. I haven't updated this library long
time.
I'm gonna look into it this weekend and let you know.

Thank you very much for your feedback.

**Comment by loverde-co** [comment]
Thanks, i will be waiting :)

**Comment by shuhrat10** [comment]
@loverde-co I've made changes. Checkout version 1.1.2
Let me know if it's still not working for you

**Comment by loverde-co** [comment]
Ok @shuhrat10 ! Thanks, i will update, test and let you know
