### ISSUE TITLE
@IBInspectable proberties not public

### ISSUE THREAD

**Issue by Blackjacx** [shuhrat10/STRatingControl#3]
Hi 

you should make your @IBInspectable properties public since they are not accessible from code otherwise! I cannot set the images for example...

Cocoapods 1.0.1
Swift 2.2

**Comment by raulperez** [comment]
Yes, it could be great. Could you do that?

**Comment by Blackjacx** [comment]
No time for that sorry :-/

**Comment by raulperez** [comment]
Could you add me as collaborator?

iPhone

**Comment by Blackjacx** [comment]
It is not my repo ...

**Comment by shuhrat10** [comment]
@Blackjacx @raulperez 
I'm made changes. Checkout v1.1.2
Feel free to open issue if it's still now working for you.
